### ISSUE TITLE
Past Reports View

### ISSUE THREAD

**Issue by jakepeyser** [yangweichen/inspection_app#1]
Truckers can view a list of the reports that they have previously submitted

**Comment by rhgrant7** [comment]
This needs to be by truck, not by driver. 

All DVIRs are only used in a per truck sense, not per driver.

**Comment by jakepeyser** [comment]
So when a user logs in, don't they see a list of all prior reports? From my understanding they do not associate with a specific truck when they authenticate

**Comment by jakepeyser** [comment]
Date filter: http://materializecss.com/forms.html#date-picker

**Comment by jakepeyser** [comment]
![report-list](https://cloud.githubusercontent.com/assets/1534503/21290086/b08e92e2-c47b-11e6-9c39-859994eace48.png)

**Comment by rhgrant7** [comment]
perfect
