### ISSUE TITLE
Trucker Log In

### ISSUE THREAD

**Issue by jakepeyser** [yangweichen/inspection_app#20]

**Comment by jakepeyser** [comment]
![login](https://cloud.githubusercontent.com/assets/1534503/21281376/13f07192-c3ba-11e6-8b3b-c7c1db77e737.png)

**Comment by jakepeyser** [comment]
Revised based on conversation about login simplification

![login](https://cloud.githubusercontent.com/assets/1534503/21289749/dba6f11c-c472-11e6-989c-7fcbe44f0ca3.png)

**Comment by yangweichen** [comment]
Looks good
